# Generated by Django 4.1 on 2022-11-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicresult',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_result', to='szz_app.topic'),
        ),
    ]
