# Generated by Django 4.1 on 2022-09-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0002_alter_questionnaire_fill_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='type',
            new_name='questionnaire_type',
        ),
    ]
