# Generated by Django 4.1 on 2022-09-21 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0003_rename_type_questionnaire_questionnaire_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questionnaire_type',
            new_name='type',
        ),
    ]
