# Generated by Django 4.1 on 2022-09-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0004_rename_questionnaire_type_questionnaire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fill_time',
            field=models.TimeField(null=True),
        ),
    ]
