# Generated by Django 4.1 on 2022-09-21 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0006_alter_questionnaire_fill_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hours', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='fill_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='szz_app.time'),
            preserve_default=False,
        ),
    ]
