# Generated by Django 4.1 on 2022-09-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0008_alter_questionnaire_fill_time_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='fill_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
