# Generated by Django 4.1 on 2022-09-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0010_alter_questionnaire_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='platform_type',
            field=models.IntegerField(choices=[(0, '本平台'), (1, '问卷星'), (2, '问卷网'), (3, '腾讯调查')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='platform_url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='state',
            field=models.IntegerField(choices=[(0, '原始状态'), (-1, '逻辑删除'), (1, '匿名')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='state',
            field=models.IntegerField(choices=[(0, '原始状态'), (-1, '逻辑删除'), (1, '匿名')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(choices=[(0, '无类型/通用类型'), (1, '社会热点'), (2, '心理'), (3, '文化'), (4, '影视'), (5, '音乐'), (6, '科技'), (7, '财经')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='state',
            field=models.IntegerField(choices=[(0, '原始状态'), (-1, '逻辑删除'), (1, '匿名')], default=0, null=True),
        ),
    ]
