# Generated by Django 4.1 on 2022-09-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0011_questionnaire_platform_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaires',
            field=models.ManyToManyField(related_name='questions', to='szz_app.question'),
        ),
    ]
