# Generated by Django 4.1 on 2022-09-22 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0012_remove_questionnaire_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='szz_app.question'),
            preserve_default=False,
        ),
    ]
