# Generated by Django 4.1 on 2022-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0015_rename_question1_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birth',
            field=models.DateField(null=True),
        ),
    ]
