# Generated by Django 4.1 on 2022-09-23 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0018_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionresult',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_result', to='szz_app.topic'),
        ),
        migrations.AlterField(
            model_name='textresult',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_result', to='szz_app.topic'),
        ),
    ]
