# Generated by Django 4.1 on 2022-09-24 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('szz_app', '0020_remove_result_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTypeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TextTypeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TopicResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='textresult',
            name='result',
        ),
        migrations.RemoveField(
            model_name='textresult',
            name='topic',
        ),
        migrations.AlterField(
            model_name='result',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='szz_app.questionnaire'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('questionnaire', 'user')},
        ),
        migrations.DeleteModel(
            name='OptionResult',
        ),
        migrations.DeleteModel(
            name='TextResult',
        ),
        migrations.AddField(
            model_name='topicresult',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='szz_app.result'),
        ),
        migrations.AddField(
            model_name='topicresult',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_result', to='szz_app.topic'),
        ),
        migrations.AddField(
            model_name='texttyperesult',
            name='topic_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_type_result', to='szz_app.topicresult'),
        ),
        migrations.AddField(
            model_name='optiontyperesult',
            name='topic_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='option_type_result', to='szz_app.topicresult'),
        ),
    ]
