# Generated by Django 4.1 on 2022-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0022_alter_topicresult_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optiontyperesult',
            old_name='option',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='texttyperesult',
            old_name='text',
            new_name='answer',
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.IntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '文本题')]),
        ),
    ]
