# Generated by Django 4.1 on 2022-10-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szz_app', '0023_rename_option_optiontyperesult_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover', verbose_name='问题封面'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='cover',
            field=models.ImageField(null=True, upload_to='cover', verbose_name='回答封面'),
        ),
    ]
